# Deploy with gcloud app deploy app.yaml -v latest to deploy to App Engine Flexible Environment on GCP

# Name of our service inside App Engine
service: informer-bot-xxxxxx
runtime: custom
env: flexible

# If you want to connect via socket
beta_settings:
    cloud_sql_instances: 'instance-name:location:informer-db'

# Necessary since we won't be opening an HTTP end-point
vm_health_check:
 enable_health_check: False

# Comment this out if you enable the CMD in docker. Replace 1234567 with your Telegram API user ID
entrypoint: python bot.py 1234567
instance_class: F4

# You will want memory over CPU
resources:
  cpu: 2
  memory_gb: 5
  disk_size_gb: 15

